# Generated by Django 3.1.7 on 2021-03-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210301_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timed_penalty_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='answer_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='down_vote_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='question_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reputation',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='up_vote_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
