# Generated by Django 3.1.7 on 2021-03-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210303_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reputation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
