# Generated by Django 3.1.7 on 2021-03-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210316_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='answer_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='question_count',
        ),
    ]
