# Generated by Django 3.1.7 on 2021-03-01 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_answered', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(blank=True, default=0, null=True)),
                ('down_vote_count', models.IntegerField(blank=True, default=0, null=True)),
                ('up_vote_count', models.IntegerField(blank=True, default=0, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('accepted_answer_id', models.IntegerField(blank=True, null=True)),
                ('answer_count', models.IntegerField(blank=True, default=0, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('closed_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
