# Generated by Django 3.1.7 on 2021-03-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
