# Generated by Django 3.1.7 on 2021-03-11 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='users_upvote',
            field=models.ManyToManyField(blank=True, null=True, related_name='question_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
