# Generated by Django 3.1.7 on 2021-03-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210316_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='accepted_answer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
