# Generated by Django 3.1.7 on 2021-03-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20210316_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_count',
        ),
    ]
