# Generated by Django 3.1.7 on 2021-03-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20210315_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_accepted',
        ),
    ]
